var Names = {};

Names.list = ["Phobiashy","Tree","RapiDash","Blossomforth","Bulk","Cumulo Chaser","Cloudchaser","Crafty Crate","Daring","Muffin Courier D","Dumb-Bell","Flash Sent","Stormy Skies","Sunny Skies","Flitter","Hoops","Lightning Dust","Lucy Packard","The Royal G","Stellar Eclipse","Thunderlane","Fleetfoot","Soarin","Spitfire","Blaze","Fire Streak","High Winds","Lightning Streak","Misty Fly","Silver Lining","Surprise","Wave Chill","Crescent Moon","Fast Clip","Ring Out","Whiplash","April Showers","Big Shot","Blue October","Blueberry Muffin","Bluebell","Blueberry Cloud","Blueberry Punch","Bluebird Happiness","Bon Voyage","Buddy","Candy Floss","Cerulean Skies","Chocolate Blueberry","Cinnamon Swirl","Cloud Break","Cloud Kicker","Cloud Showers","Compass Star","Cosmic","Cream Tangerine","Deep Blue","Descent","Dewdrop","Downdraft","Drizzle","Dust Devil","E'Stop","Electric Blue","Endless Clouds","Foggy Fleece","Golden Glory","Graceful Falls","Grape Soda","Great Scott","Helia","High Note","High Spirits",
"Honey Rays","Jack Hammer","Jetstream","Juicy Fruit","Laurette","Lavender Skies","Lightning Bolt","Lilac Sky","Lime Jelly","Madden","Merry May","Midnight Strike","Nightingale","Nightjar","Northern Lights","Orange Box","Orange Swirl","Parasol","Parula","Pink Cloud","Pizzelle","Prim Posy","Prism Glider","Pumpkin Tart","Q. T. Prism","Rain Dance","Rainbow Blaze","Rainbow Drop","Rainbow Swoop","Rainbowshine","Ralph","Riverdance","Rosewing","Sandstorm","Sassaflash","Score","Serenity","Sightseer","Silver Script","Silverspeed","Silverwing","Sky Flower","Skyra","Slipstream","Snow Flight","Snowslide","Special Delivery","Spring Skies","Sprinkle Medley","Star Hunter","Starburst","Stardancer","Starry Eyes","Starsong","Sugar Apple","Steam Roller","Stormbreaker","Stormfeather","Strawberry Sunrise","Sugar Twist","Sunburst","Sunlight","Clouds Cheer","Sunlight Spring","Sunny Rays","Sunshower Raindrops","Sunstone","The Tenth Doctor","Third Whooves","Thorn","Tiger Lily","Tracy Flash","Shutterfly","Tropical Storm",
"Whitewash","Wild Fire","Cadet Wild Flower","Wind Chill","Wing Wishes","Papa Crystal G","Berryshine","Caramel","Dr. Hooves","Emerald Green","Globe Trotter","Golden Harvest","Luckette","Lucky Clover","Meadow Song","Noteworthy","Peachy Sweet","Perfect Pace","Rivet","Collector Teddie Safari","Twilight Sky","Twili","Wisp",
"Calamity", "Whisper Powerhooves", "Morning Glory", "Windsheer", "Absolutely Everything", "Autumn Leaf", "Atom Smasher", "Brass", "Red Racer", "Scootaloo", "Flurry Fluster", "Flare", "Murky", "Skyline", "Subway", "Radiant Star"];

Names.random = function()
{
    return Names.list[Utilities.randomIntInRange(0, Names.list.length - 1)];
};